// Exported separately from AppContext component to satisfy fast-refresh rules
export const topics = {
  ml: [
    { id: 'what-is-ml', label: 'What is ML?', icon: '🧠' },
    { id: 'linear-regression', label: 'Linear Regression', icon: '📈' },
    { id: 'logistic-regression', label: 'Logistic Regression', icon: '🔀' },
    { id: 'decision-tree', label: 'Decision Trees', icon: '🌳' },
    { id: 'knn', label: 'k-Nearest Neighbors', icon: '📍' },
    { id: 'svm', label: 'Support Vector Machines', icon: '⚔️' },
    { id: 'bayesian-learning', label: 'Bayesian Learning', icon: '🎲' },
    { id: 'ensemble-learning', label: 'Ensemble Learning & Bagging', icon: '🌲' },
    { id: 'boosting', label: 'Ensemble Learning – II (Boosting)', icon: '🚀' },
    { id: 'clustering', label: 'Unsupervised Learning (Clustering)', icon: '🔮' },
    { id: 'model-evaluation', label: 'Model Evaluation & Responsible AI', icon: '⚖️' },
  ],
  dnn: [
    { id: 'what-is-dnn', label: 'What is DNN?', icon: '🕸️' },
    { id: 'perceptron', label: 'Perceptron', icon: '⚡' },
    { id: 'mlp', label: 'Multi Layer Perceptron', icon: '🧬' },
    { id: 'linear-neuron-regression', label: 'Linear Neurons for Regression', icon: '📉' },
    { id: 'linear-neuron-classification', label: 'Linear Neurons for Classification', icon: '🎯' },
    { id: 'cnn', label: 'Convolutional Neural Networks', icon: '🖼️' },
    { id: 'deep-cnn', label: 'Deep CNN Architectures', icon: '🏛️' },
    { id: 'transfer-learning', label: 'Transfer Learning & Fine-Tuning', icon: '🔁' },
    { id: 'rnn', label: 'Recurrent Neural Networks', icon: '🔄' },
    { id: 'deep-rnn', label: 'Deep Recurrent Neural Networks', icon: '🧠' },
    { id: 'attention', label: 'Attention Mechanism', icon: '🔍' },
    { id: 'transformer', label: 'Transformer Architecture', icon: '⚡' },
    { id: 'optimization-deep-models', label: 'Optimization of Deep Models', icon: '⚙️' },
    { id: 'regularization-deep-models', label: 'Regularization for Deep Models', icon: '🛡️' },
  ],
}
